version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/todo
  mongo:
    image: "mongo:5.0.3"
    ports:
      - "27017:27017"